web_profiler:
    #  Invalid type for path "web_profiler.toolbar". Expected "bool", but got "string".
    toolbar: "%env(boolean:SF_PROFILER_TOOLBAR)%"
    intercept_redirects: false

framework:
    profiler: { only_exceptions: false }
