web_profiler:
    #  Invalid type for path "web_profiler.toolbar". Expected boolean, but got string.
    toolbar: "%env(bool:SF_PROFILER_TOOLBAR)"
    intercept_redirects: false

framework:
    profiler: { only_exceptions: false }
