web_profiler:
    #  Environment variables "bool:SF_PROFILER_TOOLBAR" are never used. Please, check your container's configuration.
    toolbar: "%env(bool:SF_PROFILER_TOOLBAR)%"
    intercept_redirects: false

framework:
    profiler: { only_exceptions: false }
